### ISSUE TITLE
using hashed version of js files

### ISSUE THREAD

**Issue by dohomi** [bluebeel/now-nuxt#9]
Hello
I'd like (for caching purpose) having hashed version of filenames. Otherwise browser cached files will be delivered for users and this can lead to unexpected behaviour.
Currently this builder only works with
```
    filenames: {
      app: '[name].js',
      chunk: '[name].js'
    }
```
Any idea how this could be solved? 
Thanks

**Comment by bluebeel** [comment]
I put this option to not have to write custom routes in the now.json file.
If you remove this option and leave the hashes by default, you will have to write all the routes yourself to map the files.

**Comment by dohomi** [comment]
@bluebeel can you clarify this in the `README` for other devs? I'm concerned that non-hashed version will never be a choice for any website because returning visitors might receive broken websites if breaking changes are made to the JS files.
